---
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: ansible
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: Create an instance for Debian
    image: "6nsh/debian:molecule-${MOLECULE_DISTRO:-bullseye}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: Create an instance for CentOS
    image: "6nsh/centos:molecule-${MOLECULE_DISTRO:-stream8}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
